version: '3.8'

services:
  api:
    build:
      context: ../ecomm-backend
      dockerfile: Dockerfile
    container_name: flask-api
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecomm-frontend
    ports:
      - "80:80"
    depends_on:
      - api
